language: node_js
os:
 - linux
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
notifications:
  email: false
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
before_script:
  - 'if [ -n "${REACT-}" ]; then npm install --no-save "react@~${REACT}" "react-dom@~${REACT}"; fi'
script:
  - 'if [ -n "${PRETEST-}" ]; then yarn run pretest ; fi'
  - 'if [ -n "${TEST-}" ]; then yarn run tests-only ; fi'
sudo: false
env:
  - REACT=0.14.9
  - REACT=15.0
  - REACT=15
  - REACT=16.0
  - REACT=16